### PR TITLE
pair programming working on portfolio accessibility

### PR DESCRIPTION
**Pull request by Bria222**
- Page titles - https://github.com/Bria222/Bria222.github.io/pull/9/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R13

- Image text alternatives-No issues found
- Text headings-No issues found
- color contrast-No issues found
- Resize-No issues found
- Interactions-No issues found
- Moving content-No issues found
- multimedia-No issues found
- The basic structure of the page-No issues found

### CODE REVIEW

**Review by sja-thedude — COMMENTED** [review]
## Invalid Code Review Request ❌

Hi <STUDENT_MENTION>, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that has commit only by you. This is a pair programming project which requires all the members of the pair programming group to commit. Also, this project is submitted for the 3rd review but it doesn't show the previous reviewers' review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Bria222** [comment]
@sja-thedude we went through the project together they could not get errors that is why there are no commits

**Comment by sja-thedude** [comment]
> @sja-thedude we went through the project together they could not get errors that is why there are no commits 

@Bria222 this is pair programming project and it's mandatory for all the members of the pair programming group to commit.

**Comment by Bria222** [comment]
@sja-thedude  and also this is my first submission I don't know why it's showing that I have submitted twice and I really haven't I don't know what the problem really is.

**Comment by sja-thedude** [comment]
> @sja-thedude  and also this is my first submission I don't know why it's showing that I have submitted twice and I really haven't I don't know what the problem really is. 

Oh okay @Bria222 , I think some technical error maybe. You can submit with adding commits of both the members. If your project is not approved then let me know I will ask senior code reviewer about the error.

**Comment by Bria222** [comment]
@sja-thedude Thanks so much for your feedback i will check do the required changes

**Comment by Bria222** [comment]
@sja-thedude  i have made the changes required kindly check  thanks

**Comment by Bria222** [comment]
Screenshot (177)
@sja-thedude this is the error am getting on submission

**Comment by sja-thedude** [comment]
> Screenshot (177)
> 
> @sja-thedude this is the error am getting on submission

I think some technical problem. I have informed about this , hopefully it will be solved soon.

**Comment by Bria222** [comment]
@sja-thedude thanks

**Review by thecodechaser — APPROVED** [review]
## STATUS: APPROVED 🟢

## Hi @Bria222 and Team👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good accessibility report. ✔️

## Optional suggestions
I am marking these changes optional because of the dashboard error, you lost one code review attempt but I will strongly suggest considering these suggested changes.
- [ ] [optional] Please add `<label>` for all form input controls. It helps for accessibility, e.g. screen-readers.
As in your design, there's no `label`, You can use hidden attributes for your labels so they will not display but will be available for accessibility.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
